apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devcoe-azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
